---
abstract: 'Interface to the mypeople service for p5-hubot'
author:
  - 'Hyungsuk Hong <hshong@perl.kr>'
build_requires:
  Test::More: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hubot-Adapter-Mypeople
requires:
  AnyEvent::HTTPD: 0
  AnyEvent::Mypeople::Client: 0
  Encode: 0
  JSON::XS: 0
  Moose: 0
  namespace::autoclean: 0
version: 0.0.3
